class BibleAssetManifestEntry {
  const BibleAssetManifestEntry(
    this.id,
    this.file,
    this.en,
    this.am,
    this.chapters,
  );

  final String id;
  final String file;
  final String en;
  final String am;
  final int chapters;
}

String bibleAssetPath(String lang) => 'assets/80-weahadu-main/data/$lang/';

const bibleAssetManifest = [
  BibleAssetManifestEntry(
    'genesis',
    '01-genesis.json',
    'Genesis',
    'ኦሪት ዘፍጥረት',
    50,
  ),
  BibleAssetManifestEntry('exodus', '02-exodus.json', 'Exodus', 'ኦሪት ዘጸአት', 40),
  BibleAssetManifestEntry(
    'leviticus',
    '03-leviticus.json',
    'Leviticus',
    'ኦሪት ዘሌዋውያን',
    27,
  ),
  BibleAssetManifestEntry(
    'numbers',
    '04-numbers.json',
    'Numbers',
    'ኦሪት ዘቍጽልቍ',
    36,
  ),
  BibleAssetManifestEntry(
    'deuteronomy',
    '05-deuteronomy.json',
    'Deuteronomy',
    'ኦሪት ዘዳግም',
    34,
  ),
  BibleAssetManifestEntry('joshua', '06-joshua.json', 'Joshua', 'መጽሐፈ ኢያሱ', 24),
  BibleAssetManifestEntry(
    'judges',
    '07-judges.json',
    'Judges',
    'መጽሐፈ መሳፍንት',
    21,
  ),
  BibleAssetManifestEntry('ruth', '08-ruth.json', 'Ruth', 'መጽሐፈ ሩት', 4),
  BibleAssetManifestEntry(
    '1-samuel',
    '09-1samuel.json',
    '1 Samuel',
    'መጽሐፈ ሳሙኤል ቀዳማዊ',
    31,
  ),
  BibleAssetManifestEntry(
    '2-samuel',
    '10-2 samuel.json',
    '2 Samuel',
    'መጽሐፈ ሳሙኤል ካልዕ',
    24,
  ),
  BibleAssetManifestEntry(
    '1-kings',
    '11-1 kings.json',
    '1 Kings',
    'መጽሐፈ ነገሥት ቀዳማዊ',
    22,
  ),
  BibleAssetManifestEntry(
    '2-kings',
    '12-2 kings.json',
    '2 Kings',
    'መጽሐፈ ነገሥት ካልዕ',
    25,
  ),
  BibleAssetManifestEntry(
    '1-chronicles',
    '13-1 chronicles.json',
    '1 Chronicles',
    'መጽሐፈ ዜና መዋዕል ቀዳማዊ',
    29,
  ),
  BibleAssetManifestEntry(
    '2-chronicles',
    '14-2 chronicles.json',
    '2 Chronicles',
    'መጽሐፈ ዜና መዋዕል ካልዕ',
    36,
  ),
  BibleAssetManifestEntry(
    'jubilees',
    '15-kufale.json',
    'Jubilees',
    'መጽሐፈ ኩፋሌ',
    34,
  ),
  BibleAssetManifestEntry('enoch', '16-enoch.json', 'Enoch', 'መጽሐፈ ሄኖክ', 42),
  BibleAssetManifestEntry('ezra', '17-ezra.json', 'Ezra', 'መጽሐፈ ዕዝራ', 10),
  BibleAssetManifestEntry(
    'nehemiah',
    '18-nehemiah.json',
    'Nehemiah',
    'መጽሐፈ ነህምያ',
    13,
  ),
  BibleAssetManifestEntry(
    '3-book-of-ezra',
    '19-ezrasutuel.json',
    '3 Book of Ezra',
    'መጽሐፈ ዕዝራ ሱቱኤል',
    13,
  ),
  BibleAssetManifestEntry(
    '2nd-book-of-ezra',
    '20-ezrakale.json',
    '2nd Book of Ezra',
    'መጽሐፈ ዕዝራ ካልእ',
    9,
  ),
  BibleAssetManifestEntry(
    'book-of-tobit',
    '21-tobit.json',
    'Book of Tobit',
    'መጽሐፈ ጦቢት',
    14,
  ),
  BibleAssetManifestEntry(
    'book-of-judith',
    '22-yodit.json',
    'Book of Judith',
    'መጽሐፈ ዮዲት',
    16,
  ),
  BibleAssetManifestEntry(
    'esther',
    '23-esther.json',
    'Esther',
    'መጽሐፈ አስቴር',
    11,
  ),
  BibleAssetManifestEntry(
    '1-maccabees',
    '24-1 maccabees.json',
    '1 Maccabees',
    'መጽሐፈ መቃብያን ቀዳማዊ',
    36,
  ),
  BibleAssetManifestEntry(
    '2-maccabees',
    '25-2 maccabees.json',
    '2 Maccabees',
    'መጽሐፈ መቃብያን ካልእ',
    21,
  ),
  BibleAssetManifestEntry(
    '3-maccabees',
    '26-3 maccabees.json',
    '3 Maccabees',
    'መጽሐፈ መቃብያን ሣልስ',
    10,
  ),
  BibleAssetManifestEntry('job', '27-job.json', 'Job', 'መጽሐፈ ኢዮብ', 42),
  BibleAssetManifestEntry(
    'psalms',
    '28-psalms.json',
    'Psalms',
    'መዝሙረ ዳዊት',
    151,
  ),
  BibleAssetManifestEntry(
    'proverbs',
    '29-proverbs.json',
    'Proverbs',
    'መጽሐፈ ምሳሌ',
    24,
  ),
  BibleAssetManifestEntry(
    'book-of-admonition',
    '30-admonition.json',
    'Book of Admonition',
    'መጽሐፈ ተግሣጽ',
    6,
  ),
  BibleAssetManifestEntry(
    'wisdom-of-solomon',
    '31-wisdom of solomon.json',
    'Wisdom of Solomon',
    'መጽሐፈ ጥበብ',
    19,
  ),
  BibleAssetManifestEntry(
    'ecclesiastes',
    '32-ecclesiastes.json',
    'Ecclesiastes',
    'መጽሐፈ መክብብ',
    12,
  ),
  BibleAssetManifestEntry(
    'song-of-solomon',
    '33-song of solomon.json',
    'Song of Solomon',
    'መኃልየ መኃልይ ዘሰሎሞን',
    8,
  ),
  BibleAssetManifestEntry(
    'book-of-sirach',
    '34-sirach.json',
    'Book of Sirach',
    'መጽሐፈ ሲራክ',
    51,
  ),
  BibleAssetManifestEntry(
    'isaiah',
    '35-isaiah.json',
    'Isaiah',
    'ትንቢተ ኢሳይያስ',
    66,
  ),
  BibleAssetManifestEntry(
    'jeremiah',
    '36-jeremiah.json',
    'Jeremiah',
    'ትንቢተ ኤርምያስ',
    52,
  ),
  BibleAssetManifestEntry('baruch', '37-Baruch.json', 'Baruch', 'መጽሐፈ ባሮክ', 5),
  BibleAssetManifestEntry(
    'lamentations',
    '38-lamentations.json',
    'Lamentations',
    'ሰቆቃወ ኤርምያስ',
    5,
  ),
  BibleAssetManifestEntry(
    'thr-letter-of-jeremiah',
    '39-terefermias.json',
    'Letter of Jeremiah',
    'ተረፈ ኤርምያስ',
    1,
  ),
  BibleAssetManifestEntry(
    'teref-baruch',
    '40-Teref Baruch.json',
    'Teref Baruch',
    'ተረፈ ባሮክ',
    5,
  ),
  BibleAssetManifestEntry(
    'ezekiel',
    '41-ezekiel.json',
    'Ezekiel',
    'ትንቢተ ሕዝቄኤል',
    48,
  ),
  BibleAssetManifestEntry(
    'daniel',
    '42-daniel.json',
    'Daniel',
    'ትንቢተ ዳንኤል',
    14,
  ),
  BibleAssetManifestEntry('hosea', '43-hosea.json', 'Hosea', 'ትንቢተ ሆሴዕ', 14),
  BibleAssetManifestEntry('amos', '44-amos.json', 'Amos', 'ትንቢተ ዓሞጽ', 9),
  BibleAssetManifestEntry('micah', '45-micah.json', 'Micah', 'ትንቢተ ሚክያስ', 7),
  BibleAssetManifestEntry('joel', '46-joel.json', 'Joel', 'ትንቢተ ኢዮኤል', 3),
  BibleAssetManifestEntry(
    'obadiah',
    '47-obadiah.json',
    'Obadiah',
    'ትንቢተ አብድዩ',
    1,
  ),
  BibleAssetManifestEntry('jonah', '48-jonah.json', 'Jonah', 'ትንቢተ ዮናስ', 4),
  BibleAssetManifestEntry('nahum', '49-nahum.json', 'Nahum', 'ትንቢተ ናሆም', 3),
  BibleAssetManifestEntry(
    'habakkuk',
    '50-habakkuk.json',
    'Habakkuk',
    'ትንቢተ ዕንባቆም',
    3,
  ),
  BibleAssetManifestEntry(
    'zephaniah',
    '51-zephaniah.json',
    'Zephaniah',
    'ትንቢተ ጸፎንያስ',
    3,
  ),
  BibleAssetManifestEntry('haggai', '52-haggai.json', 'Haggai', 'ትንቢተ ሐጌ', 2),
  BibleAssetManifestEntry(
    'zechariah',
    '53-zechariah.json',
    'Zechariah',
    'ትንቢተ ዘካርያስ',
    14,
  ),
  BibleAssetManifestEntry(
    'malachi',
    '54-malachi.json',
    'Malachi',
    'ትንቢተ ሚልክያስ',
    4,
  ),
  BibleAssetManifestEntry(
    'matthew',
    '55-matthew.json',
    'Matthew',
    'የማቴዎስ ወንጌል',
    28,
  ),
  BibleAssetManifestEntry('mark', '56-mark.json', 'Mark', 'የማርቆስ ወንጌል', 16),
  BibleAssetManifestEntry('luke', '57-luke.json', 'Luke', 'የሉቃስ ወንጌል', 24),
  BibleAssetManifestEntry('john', '58-john.json', 'John', 'የዮሐንስ ወንጌል', 21),
  BibleAssetManifestEntry('acts', '59-act.json', 'Acts', 'የሐዋርያት ሥራ', 28),
  BibleAssetManifestEntry(
    'romans',
    '60-romans.json',
    'Romans',
    'ወደ ሮሜ ሰዎች',
    16,
  ),
  BibleAssetManifestEntry(
    '1-corinthians',
    '61-1_corinthians.json',
    '1 Corinthians',
    '1ኛ ወደ ቆሮንቶስ ሰዎች',
    16,
  ),
  BibleAssetManifestEntry(
    '2-corinthians',
    '62-2_corinthians.json',
    '2 Corinthians',
    '2ኛ ወደ ቆሮንቶስ ሰዎች',
    13,
  ),
  BibleAssetManifestEntry(
    'galatians',
    '63-galatians.json',
    'Galatians',
    'ወደ ገላትያ ሰዎች',
    6,
  ),
  BibleAssetManifestEntry(
    'ephesians',
    '64-ephesians.json',
    'Ephesians',
    'ወደ ኤፌሶን ሰዎች',
    6,
  ),
  BibleAssetManifestEntry(
    'philippians',
    '65-philippians.json',
    'Philippians',
    'ወደ ፍልጵስዩስ ሰዎች',
    4,
  ),
  BibleAssetManifestEntry(
    'colossians',
    '66-colossians.json',
    'Colossians',
    'ወደ ቆላስይስ ሰዎች',
    4,
  ),
  BibleAssetManifestEntry(
    '1-thessalonians',
    '67-1_thessalonians.json',
    '1 Thessalonians',
    '1ኛ ወደ ተሰሎንቄ ሰዎች',
    5,
  ),
  BibleAssetManifestEntry(
    '2-thessalonians',
    '68-2_thessalonians.json',
    '2 Thessalonians',
    '2ኛ ወደ ተሰሎንቄ ሰዎች',
    3,
  ),
  BibleAssetManifestEntry(
    '1-timothy',
    '69-1_timothy.json',
    '1 Timothy',
    '1ኛ ወደ ጢሞቴዎስ',
    6,
  ),
  BibleAssetManifestEntry(
    '2-timothy',
    '70-2_timothy.json',
    '2 Timothy',
    '2ኛ ወደ ጢሞቴዎስ',
    4,
  ),
  BibleAssetManifestEntry('titus', '71-titus.json', 'Titus', 'ወደ ቲቶ', 3),
  BibleAssetManifestEntry(
    'philemon',
    '72-philemon.json',
    'Philemon',
    'ወደ ፊልሞና',
    1,
  ),
  BibleAssetManifestEntry(
    'hebrews',
    '73-hebrews.json',
    'Hebrews',
    'ወደ ዕብራውያን',
    13,
  ),
  BibleAssetManifestEntry(
    '1-peter',
    '74-1_peter.json',
    '1 Peter',
    '1ኛ የጴጥሮስ መልእክት',
    5,
  ),
  BibleAssetManifestEntry(
    '2-peter',
    '75-2_peter.json',
    '2 Peter',
    '2ኛ የጴጥሮስ መልእክት',
    3,
  ),
  BibleAssetManifestEntry(
    '1-john',
    '76-1_john.json',
    '1 John',
    '1ኛ የዮሐንስ መልእክት',
    5,
  ),
  BibleAssetManifestEntry(
    '2-john',
    '77-2_john.json',
    '2 John',
    '2ኛ የዮሐንስ መልእክት',
    1,
  ),
  BibleAssetManifestEntry(
    '3-john',
    '78-3-john.json',
    '3 John',
    '3ኛ የዮሐንስ መልእክት',
    1,
  ),
  BibleAssetManifestEntry('james', '79-james.json', 'James', 'የያዕቆን መልእክት', 5),
  BibleAssetManifestEntry('jude', '80-jude.json', 'Jude', 'የይሁዳ መልእክት', 1),
  BibleAssetManifestEntry(
    'revelation',
    '81-revelation.json',
    'Revelation',
    'የዮሐንስ ራዕይ',
    22,
  ),
];
